# Generated by Django 3.2.16 on 2023-01-09 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_time', models.DateTimeField()),
                ('hostname', models.CharField(max_length=255)),
                ('emocheck_version', models.CharField(max_length=255)),
                ('is_infected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotetProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=255)),
                ('process_id', models.IntegerField()),
                ('image_path', models.CharField(max_length=255)),
                ('registry_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emocheck.result')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
